import os
from pathlib import Path
from datetime import datetime, timezone
from dotenv import load_dotenv
from google import genai
from google.genai import types

from test_rag import retrieve_live_context
from schemas import ScoutAssessment, LogisticsReroutePlan

# Load Environment
env_path = Path(__file__).resolve().parent / ".env"
if not env_path.exists():
    env_path = Path(__file__).resolve().parent.parent / ".env"
load_dotenv(dotenv_path=env_path)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
ai_client = genai.Client(api_key=GEMINI_API_KEY)

def run_end_to_end_simulation(crisis_scenario: str):
    print("==================================================")
    print(" 🚀 RESILIENTINDIA AI: END-TO-END SIMULATION RUN")
    print("==================================================")
    print(f"Scenario: {crisis_scenario}\n")

    # Step A: Live RAG Retrieval
    print("[1/4] Querying Live Intel from Supabase Vector Store...")
    intel_context = retrieve_live_context(crisis_scenario)
    
    # Step B: Scout Agent Execution
    print("[2/4] Executing Geopolitical Scout Agent...")
    scout_prompt = f"SCENARIO: {crisis_scenario}\n\n{intel_context}"
    scout_response = ai_client.models.generate_content(
        model="gemini-2.5-flash",
        contents=scout_prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=ScoutAssessment,
        ),
    )
    scout_result = ScoutAssessment.model_validate_json(scout_response.text)
    print(f"  └─ Risk Score Calculated: {scout_result.risk_score}/100 ({scout_result.confidence_level})")

    # Step C: Logistics Architect Agent Execution
    print("[3/4] Executing Adaptive Logistics Architect Agent...")
    logistics_prompt = f"""
You are the Adaptive Logistics Architect for ResilientIndia AI.
Based on the Scout Assessment, calculate energy supply chain mitigation strategies.

SCOUT ASSESSMENT:
- Threat Summary: {scout_result.threat_summary}
- Risk Score: {scout_result.risk_score}
- Corridors Affected: {scout_result.affected_corridors}

If Risk Score > 70:
1. Recommend Cape of Good Hope rerouting (+10 to 14 days delay).
2. Calculate Strategic Petroleum Reserve (SPR) drawdown rates (Visakhapatnam, Mangaluru, Padur).
3. Generate a Markdown Executive Dossier for government decision-makers.
"""
    logistics_response = ai_client.models.generate_content(
        model="gemini-2.5-flash",
        contents=logistics_prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=LogisticsReroutePlan,
        ),
    )
    logistics_result = LogisticsReroutePlan.model_validate_json(logistics_response.text)
    
    # Step D: Export Executive Dossier
    print("[4/4] Exporting Executive Intelligence Dossier...")
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"EXECUTIVE_DOSSIER_{timestamp}.md"
    
#     dossier_content = f"""# 🛡️ CLASSIFIED EXECUTIVE BRIEFING: ENERGY SECURITY CRISIS
# **Generated by ResilientIndia AI Platform**
# **Timestamp (UTC):** {datetime.now(timezone.utc).isoformat()}
# **Risk Score:** {scout_result.risk_score}/100

# ---

# ## 1. Threat Assessment (Geopolitical Scout Agent)
# * **Status:** {scout_result.confidence_level} CONFIDENCE
# * **Affected Transit Corridors:** {', '.join(scout_result.affected_corridors)}
# * **Summary:** {scout_result.threat_summary}

# ---

# ## 2. Logistics & SPR Optimization (Logistics Architect Agent)
# * **Action Required:** {'YES' if logistics_result.action_required else 'NO'}
# * **Primary Bypass Route:** {logistics_result.primary_bypass_route}
# * **Estimated Transit Delay:** +{logistics_result.estimated_delay_days} Days
# * **SPR Drawdown Rate:** {logistics_result.spr_drawdown_mbpd} Million Barrels/Day
# * **Target SPR Facilities:** {', '.join(logistics_result.recommended_spr_locations)}

# ---

# ## 3. Executive Dossier Summary
# {logistics_result.dossier_markdown}
# """
#     with open(filename, "w", encoding="utf-8") as f:
#         f.write(dossier_content)

      # Generate Dossier Markdown string
    dossier_content = f"""# EXECUTIVE INTELLIGENCE DOSSIER
**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}
**Scenario:** {scenario_text}

## 1. Scout Assessment
- **Risk Score:** {scout_result.risk_score}/100
- **Confidence Level:** {scout_result.confidence_level}
- **Affected Corridors:** {', '.join(scout_result.affected_corridors)}
- **Summary:** {scout_result.threat_summary}

## 2. Adaptive Logistics Plan
- **Action Required:** {logistics_result.action_required}
- **Primary Reroute:** {logistics_result.primary_bypass_route}
- **Estimated Delay:** +{logistics_result.estimated_delay_days} Days
- **SPR Drawdown Rate:** {logistics_result.spr_drawdown_mbpd} MBPD
"""

    return {
        "scout_assessment": scout_result.model_dump(),
        "logistics_plan": logistics_result.model_dump(),
        "dossier_markdown": dossier_content
    }
        
    print(f"\n Success! Executive Dossier exported to: {filename}")
    print("==================================================")

# if __name__ == "__main__":
#     run_end_to_end_simulation("Full maritime blockade in the Strait of Hormuz following targeted attacks on oil tankers")

# if __name__ == "__main__":
#     run_end_to_end_simulation(
#         "Submarine cable failure and naval collision creating a full maritime shutdown of the Strait of Malacca"
#     )

if __name__ == "__main__":
    run_end_to_end_simulation("Routine scheduled naval maintenance exercise in international waters near the Bay of Bengal with advance diplomatic notice")




